<?php

namespace AppBundle\Repository;

/**
 * PromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPromoByCityAndDate($city){
        $langages = ['php', 'js', 'java'];

        $qb = $this->createQueryBuilder('p');
        $qb->select('p')
            ->join('p.city', 'c')
            ->add('where', $qb->expr()->in('p.langage', $langages))
            ->andWhere('c.id = :cityId')
            ->orderBy('p.langage', 'ASC')
            ->addOrderBy('p.end', 'DESC')
            ->setParameter('cityId', $city)
        ;

        return $qb->getQuery()->getResult();
    }

}
