<?php

namespace AppBundle\Repository;

/**
 * RocketChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RocketChannelRepository extends \Doctrine\ORM\EntityRepository
{
}
