imports:
    - { resource: config_dev.yml }

parameters:
    key_api_odyssey: "%env(key_api_odyssey)%"

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: true


doctrine:
    dbal:
        url: "%env(DATABASE_URL)%"